### ISSUE TITLE
Fix `preproc` method in preparing_dataset.ipynb

### ISSUE THREAD

**Issue by akarazeev** [akarazeev/REDE#1]

**Comment by akarazeev** [comment]
It seems that such plots are invalid

![screen shot 2018-03-26 at 20 12 21](https://user-images.githubusercontent.com/11920213/37922187-9396090a-3134-11e8-85f8-919a93e368b0.jpg)

**Comment by 4lukashchuk** [comment]
corrected,
had min() instead of max() (((((

**Comment by akarazeev** [comment]
Yep, now seems to be right. Thanks!
